name = "create-modpack"
author = "Techgamr"
version = "2.0.6"
description = "Create modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f36e9c10534e65ee840853a00854bb0ccaa76966007ec5e4da4c15baf359e39"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
