name = "create-modpack"
author = "Techgamr"
version = "2.0.3"
description = "Create modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f44a4b81b4776cd8741cfcf06a8851ec8680b4bf386eba76080d0a261b3d600e"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
