name = "create-modpack"
author = "Techgamr"
version = "2.0.6"
description = "Create modpack"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "555ea6d635fc26428817e8b91112cc2ef0e8bf98e1c44e7234e9e27c3b89bbbe"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
